services:
  bot:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/app/node_modules
    command: "watch"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
